name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/checkout@v4
      - name: Install modules
        run: bun install
      - name: Run tests
        run: bun test
